---
name: JDK8
on:
  push:         {branches: [ master ]}
  pull_request: {branches: [ master ]}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env: {GITHUB_TOKEN: '${{ secrets.GH_TOKEN }}', COVERALLS_TOKEN: '${{ secrets.COVERALLS_TOKEN }}'}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: {java-version: 1.8}

    - run: cp -f .ci.settings.xml $HOME/.m2/settings.xml
    - run: ./mvnw -B install org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report -DrepoToken=$COVERALLS_TOKEN
    - run: ./mvnw -B deploy -DskipTests -DaltDeploymentRepository=github-serge2nd::default::https://maven.pkg.github.com/serge2nd/maven-repo
...